### ISSUE TITLE
BigDecimal issue

### ISSUE THREAD

**Issue by deblockt** [javro/javro#24]
When we specify an avro with a bigdecimal field, this error is displayed `Avro error: e.replace is not a function`

avro sample: 
```
{
    "type": "record",
    "name": "Test",
    "fields": [
        {
            "name": "amount",
            "type": {
                "type": "bytes",
                "logicalType": "decimal",
                "precision": 15,
                "scale": 5
            },
            "doc": "The amount"
        }
    ]
}
```
![Capture d’écran de 2020-11-27 16-56-33](https://user-images.githubusercontent.com/5050163/100466656-899d0800-30d1-11eb-8599-bdb7251dc77c.png)

**Comment by delphinaubin** [comment]
Hi @deblockt, thank you for reporting this issue.

We don't handle logical types yet but in the last javro version, this avro doesn't print any error, it simply consider the amount field as a bytes field.


<img width="1116" alt="Capture d’écran 2021-04-08 à 11 57 10" src="https://user-images.githubusercontent.com/18496681/114007851-fa171b00-9861-11eb-9e67-f0a7c852aa4e.png">
